services:
  java:
    build: ./docker/
    volumes:
      - type: bind
        source: ./
        target: /app/
    working_dir: /app/
    environment:
      CH: ${CH:-ch01}
      CLASS: ${CLASS:-Main}
    command: ["sh", "-c", "echo main=$${CH}.$${CLASS} && ./gradlew run --no-daemon --continuous --console=plain -Pmain=$${CH}.$${CLASS}"]
