services:
  java:
    build: ./docker/
    volumes:
      - type: bind
        source: ./
        target: /app/
    working_dir: /app/
    environment:
      CH: ch01
      CLASS: Main
    command: ["sh", "-lc", "./gradlew run --no-daemon --continuous --console=plain -Pmain=$$CH.$$CLASS"]
